# Generated by Django 6.0.7 on 2026-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email, на который отправлен код', max_length=254, verbose_name='Электронная почта')),
                ('code_hash', models.CharField(help_text='Хэш одноразового кода (открыто не хранится)', max_length=128, verbose_name='Хэш кода')),
                ('purpose', models.CharField(choices=[('registration', 'Регистрация'), ('login', 'Вход'), ('password_reset', 'Сброс пароля')], help_text='Для чего отправлен код', max_length=20, verbose_name='Назначение')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Количество неверных вводов кода', verbose_name='Попытки ввода')),
                ('is_used', models.BooleanField(default=False, help_text='Был ли код уже использован', verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания кода', verbose_name='Создан')),
                ('expires_at', models.DateTimeField(help_text='Дата и время окончания действия кода', verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'purpose'], name='authenticat_email_ee707d_idx')],
            },
        ),
    ]
