# Generated by Django 6.1 on 2026-09-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попытки ввода'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='code_hash',
            field=models.CharField(max_length=128, verbose_name='Хэш кода'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('login', 'Вход'), ('password_reset', 'Сброс пароля')], max_length=20, verbose_name='Назначение'),
        ),
    ]
