[project]
name = "memory-test"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.7",
    "djangorestframework>=3.17.1",
    "django-filter>=26.1",
    "python-dotenv==1.0.1",
    "djangorestframework-simplejwt>=5.5.1",
]

[tool.ruff]
line-length = 79
exclude = [
    ".venv",
    "venv",
    "manage.py",
    "*/migrations",
    "*/__init__.py"
]

[tool.ruff.lint]
select = ["E", "W", "F"]

[tool.ruff.lint.per-file-ignores]
"**/settings.py" = ["E501"]

[tool.ruff.format]
quote-style = "single"

[tool.isort]
profile = "black"
line_length = 79
src_paths = ["backend"]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "backend.settings"

[dependency-groups]
dev = [
    "isort>=8.0.1",
    "ruff>=0.16.0",
    "mypy>=2.3.0",
    "django-stubs>=6.0.7",
    "pre-commit>=4.6.1",
]
flake8 = [
    "flake8>=7.3.0",
    "flake8-docstrings>=1.7.0",
    "flake8-isort>=7.0.0",
]
