[project]
name = "memory-test"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.7",
    "djangorestframework>=3.17.1",
    "django-filter>=26.1",
    "python-dotenv==1.0.1",
    "gunicorn==25.3.0",
    "django-cors-headers==4.6.0",
    "psycopg2-binary==2.9.11",
    "djangorestframework-simplejwt>=5.5.1",
]

[tool.ruff]
line-length = 79
exclude = [
    ".venv",
    "venv",
    "manage.py",
    "*/migrations",
    "*/__init__.py"
]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.ruff.isort]
known-first-party = [
    "exercises",
    "progress",
    "users",
    "api"
]

[tool.ruff.lint.per-file-ignores]
"**/settings.py" = ["E501"]
"**/__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "backend.settings"

[dependency-groups]
dev = [
    "ruff>=0.16.0",
    "mypy>=2.3.0",
    "django-stubs>=6.0.7",
    "pre-commit>=4.6.1",
]
