# Generated by Django 6.1 on 2026-08-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(verbose_name='Данные ответа (JSON)')),
                ('is_correct', models.BooleanField(verbose_name='Ответ верный')),
                ('response_time', models.FloatField(verbose_name='Время ответа (сек)')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'db_table': 'exercise_answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=10, verbose_name='уровень сложности')),
                ('started_at', models.DateTimeField(verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(verbose_name='Время окончания')),
                ('duration_seconds', models.IntegerField(verbose_name='Длительность (сек)')),
                ('success', models.BooleanField(verbose_name='Успешно выполнено')),
                ('score', models.FloatField(verbose_name='Оценка')),
                ('attempts_count', models.IntegerField(verbose_name='Количество попыток')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Сессия упражнения',
                'verbose_name_plural': 'Сессии упражнений',
                'db_table': 'exercise_sessions',
                'ordering': ['id'],
            },
        ),
    ]
