# Generated by Django 6.1 on 2026-09-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisesession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия упражнения', 'verbose_name_plural': 'Сессии упражнений'},
        ),
        migrations.RemoveField(
            model_name='exercisesession',
            name='attempts_count',
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='duration_seconds',
            field=models.PositiveIntegerField(verbose_name='Длительность (сек)'),
        ),
        migrations.AlterModelTable(
            name='exercisesession',
            table=None,
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(verbose_name='Данные ответа (JSON)')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='progress.exercisesession', verbose_name='Сессия упражнения')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
