# Generated by Django 6.1 on 2026-09-23 10:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_exercisesession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='answer_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Данные ответа (JSON)'),
        ),
    ]
