# Generated by Django 6.1 on 2026-09-24 19:37

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_choiceanswer_image_and_more'),
        ('progress', '0003_alter_userattempt_answer_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesession',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], help_text='Уровень сложности на момент прохождения.', max_length=10, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='duration_seconds',
            field=models.PositiveIntegerField(help_text='Длительность попытки в секундах (разница между finished_at и started_at).', verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='exercise',
            field=models.ForeignKey(help_text='Упражнение, которое проходило.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exercises.exercise', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='finished_at',
            field=models.DateTimeField(help_text='Время завершения попытки.', verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='score',
            field=models.FloatField(help_text='Оценка за попытку.', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='started_at',
            field=models.DateTimeField(help_text='Время начала попытки.', verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='success',
            field=models.BooleanField(help_text='Признак успешного прохождения упражнения.', verbose_name='Успешно выполнено'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, который проходил упражнение.', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='answer_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Полные данные попытки: снимок упражнения, ответ пользователя, результат проверки и метаданные (хранится в формате JSON).', verbose_name='Данные ответа (JSON)'),
        ),
        migrations.AlterField(
            model_name='userattempt',
            name='session',
            field=models.OneToOneField(help_text='Сессия, к которой относится попытка пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='progress.exercisesession', verbose_name='Сессия упражнения'),
        ),
    ]
