# Generated by Django 6.1 on 2026-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Изображение профиля пользователя.', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
