# Generated by Django 6.1 on 2026-08-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'тип задания',
                'verbose_name_plural': 'Типы заданий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=6, verbose_name='Уровень сложности')),
                ('config', models.JSONField(verbose_name='Настройки задания')),
                ('is_active', models.BooleanField(verbose_name='Доступно к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisetype', verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['title'],
            },
        ),
    ]
