# Generated by Django 6.1 on 2026-08-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('type', models.CharField(choices=[('choice', 'Выбор ответа(ов)'), ('input', 'Ручной ввод ответа'), ('ordering', 'Сортировка'), ('grouping', 'Группировка'), ('matching', 'Сопоставление'), ('drawing', 'Графический вопрос')], max_length=8, verbose_name='Тип задания')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=6, verbose_name='Уровень сложности')),
                ('question', models.TextField(max_length=1000, verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение вопроса')),
                ('audio', models.FileField(blank=True, upload_to='', verbose_name='Аудио-вопрос')),
                ('is_offline', models.BooleanField(verbose_name='Оффлайн задание')),
                ('is_active', models.BooleanField(verbose_name='Доступно к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InputAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_text', models.TextField(max_length=1000, verbose_name='Ожидаемый текст ответа')),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('trajectory', models.JSONField(verbose_name='Траектория (координаты)')),
                ('tolerance', models.SmallIntegerField(verbose_name='Допустимое отклонение')),
                ('completion_only', models.BooleanField(verbose_name='Только фиксация выполнения')),
                ('additional_image', models.ImageField(blank=True, upload_to='', verbose_name='Дополнительное изображение')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='exercises_drawinganswer_text_or_image_required')],
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('is_correct', models.BooleanField(verbose_name='Верный')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['is_correct'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='exercises_choiceanswer_text_or_image_required')],
            },
        ),
        migrations.CreateModel(
            name='GroupingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['group'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='exercises_groupinganswer_text_or_image_required')],
            },
        ),
        migrations.CreateModel(
            name='MatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField(blank=True, max_length=1000, verbose_name='Первый текст пары')),
                ('first_image', models.ImageField(blank=True, upload_to='', verbose_name='Первое изображение пары')),
                ('second_text', models.TextField(blank=True, max_length=1000, verbose_name='Второй текст пары')),
                ('second_image', models.ImageField(blank=True, upload_to='', verbose_name='Второе изображение пары')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(models.Q(('first_text', ''), _negated=True), models.Q(('first_image', ''), _negated=True), _connector='OR'), models.Q(models.Q(('second_text', ''), _negated=True), models.Q(('second_image', ''), _negated=True), _connector='OR')), name='exercises_matchinganswer_texts_or_images_required')],
            },
        ),
        migrations.CreateModel(
            name='OrderingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('position', models.SmallIntegerField(verbose_name='Порядок')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['position'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='exercises_orderinganswer_text_or_image_required')],
            },
        ),
    ]
