# Generated by Django 6.1 on 2026-08-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputanswer',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inputanswers', to='exercises.exercise', verbose_name='Задание'),
        ),
        migrations.AddConstraint(
            model_name='drawinganswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='exercises_drawinganswer_text_or_image_required', violation_error_message='Необходимо заполнить текст ответа или загрузить изображение.'),
        ),
    ]
