# Generated by Django 6.1 on 2026-09-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_inputanswer_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='exercises.exercise', verbose_name='Задание'),
        ),
    ]
