# Generated by Django 6.1 on 2026-09-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_inputanswer_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputanswer',
            name='check_method',
            field=models.CharField(choices=[('exact', 'Точное сравнение'), ('llm', 'LLM по критериям')], default='exact', max_length=20, verbose_name='Метод проверки'),
        ),
        migrations.AlterField(
            model_name='inputanswer',
            name='expected_text',
            field=models.TextField(help_text='Для exact — допустимый ответ (несколько строк на задание разрешены, для списка ответов). Для llm — критерии/рубрика, по которым оценивается ответ.', max_length=1000, verbose_name='Эталонный ответ'),
        ),
    ]
