# Generated by Django 6.1 on 2026-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_inputanswer_check_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputanswer',
            name='check_method',
            field=models.CharField(choices=[('single_answer', 'Один ответ'), ('list_answer', 'Список ответов'), ('free_answer', 'Свободная форма (пока не реализовано)')], default='single_answer', max_length=20, verbose_name='Способ проверки'),
        ),
        migrations.AlterField(
            model_name='inputanswer',
            name='expected_text',
            field=models.CharField(max_length=1000, verbose_name='Эталонный ответ'),
        ),
    ]
