# Generated by Django 6.1 on 2026-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_inputanswer_check_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceanswer',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение ответа.', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='is_correct',
            field=models.BooleanField(help_text='Признак правильности варианта (используется при проверке и показе эталона).', verbose_name='Верный'),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое содержание ответа.', max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='additional_image',
            field=models.ImageField(blank=True, help_text='Эталонное или вспомогательное изображение для проверки графического ответа.', upload_to='', verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='completion_only',
            field=models.BooleanField(help_text='Если True, достаточно просто зафиксировать факт выполнения.', verbose_name='Только фиксация выполнения'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение ответа.', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое содержание ответа.', max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='tolerance',
            field=models.SmallIntegerField(blank=True, help_text='Допустимое отклонение от эталонной траектории.', null=True, verbose_name='Допустимое отклонение'),
        ),
        migrations.AlterField(
            model_name='drawinganswer',
            name='trajectory',
            field=models.JSONField(blank=True, help_text='Координаты траектории рисунка пользователя.', null=True, verbose_name='Траектория (координаты)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='audio',
            field=models.FileField(blank=True, help_text='Аудиофайл к заданию (например, для аудирования).', upload_to='', verbose_name='Аудио-вопрос'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания упражнения (автоматически).', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(help_text='Краткое описание задания для пользователя (цели, формат).', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', help_text='Сложность задания: easy, medium, hard (влияет на начисление баллов).', max_length=6, verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение к вопросу.', upload_to='', verbose_name='Изображение вопроса'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_active',
            field=models.BooleanField(help_text='Флаг доступности упражнения для прохождения.', verbose_name='Доступно к решению'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question',
            field=models.TextField(help_text='Основной текст вопроса/задания, который видит пользователь.', max_length=1000, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(help_text='Название упражнения, отображаемое в списке и карточке задания.', max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[(None, 'Выберите тип задания'), ('choice', 'Выбор ответа(ов)'), ('input', 'Ручной ввод ответа'), ('ordering', 'Сортировка'), ('grouping', 'Группировка'), ('matching', 'Сопоставление'), ('drawing', 'Графическое задание'), ('offline', 'Офлайн задание')], help_text='Тип упражнения: choice, input, ordering, grouping, matching, drawing, offline.', max_length=8, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='groupinganswer',
            name='group',
            field=models.CharField(help_text="Имя группы/категории, к которой относится элемент (например, 'фрукты').", max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groupinganswer',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение ответа.', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='groupinganswer',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое содержание ответа.', max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='inputanswer',
            name='check_method',
            field=models.CharField(choices=[('single_answer', 'Один ответ'), ('list_answer', 'Список ответов'), ('free_answer', 'Свободная форма (пока не реализовано)')], default='single_answer', max_length=13, verbose_name='Способ проверки'),
        ),
        migrations.AlterField(
            model_name='matchinganswer',
            name='first_image',
            field=models.ImageField(blank=True, help_text='Изображение первого элемента пары.', upload_to='', verbose_name='Первое изображение пары'),
        ),
        migrations.AlterField(
            model_name='matchinganswer',
            name='first_text',
            field=models.TextField(blank=True, help_text='Текст первого элемента пары для сопоставления.', max_length=1000, verbose_name='Первый текст пары'),
        ),
        migrations.AlterField(
            model_name='matchinganswer',
            name='second_image',
            field=models.ImageField(blank=True, help_text='Изображение второго элемента пары.', upload_to='', verbose_name='Второе изображение пары'),
        ),
        migrations.AlterField(
            model_name='matchinganswer',
            name='second_text',
            field=models.TextField(blank=True, help_text='Текст второго элемента пары для сопоставления.', max_length=1000, verbose_name='Второй текст пары'),
        ),
        migrations.AlterField(
            model_name='orderinganswer',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение ответа.', upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orderinganswer',
            name='position',
            field=models.SmallIntegerField(help_text='Ожидаемый порядковый номер элемента в правильной последовательности.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='orderinganswer',
            name='text',
            field=models.TextField(blank=True, help_text='Текстовое содержание ответа.', max_length=1000, verbose_name='Текст'),
        ),
    ]
