# Generated by Django 6.1 on 2026-09-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_choiceanswer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceanswer',
            name='answer_mode',
            field=models.CharField(choices=[('single_answer', 'Один вариант'), ('multiple_answers', 'Несколько вариантов')], default='single_answer', help_text='Общий для всех вариантов этого задания: ожидается один выбранный ответ или несколько.', max_length=16, verbose_name='Режим ответа'),
        ),
    ]
